In [128]:
import pandas as pd
import numpy as np
import re
import warnings
warnings.filterwarnings('ignore')
path='../../../../ukb/data/Genetic/'

path_model='../../../../ukb/data/'

import matplotlib.pyplot as plt
import seaborn as sns
import datetime as dt

from OSGridConverter import grid2latlong

'''
Helper function to find out columns containing specific text
'''
def findcols(df,text):
    return [col for col in df.columns if text in col]

In [139]:
import os
os.listdir(path)

['ADoutput_chrom14.csv',
 'SNPlookupfileUKB_ADSNPs.csv',
 'PDoutput_chrom10.csv',
 'PDoutput_chrom3.ukb49777_cal_chr3_v2_s488264',
 'ADoutput_chrom8.csv',
 'ADoutput_chrom20.csv',
 'PDoutput_chrom12.csv',
 'PDoutput_chrom11.csv',
 'PDoutput_chrom3.csv',
 'ADoutput_chrom7.csv',
 'PDoutput_chrom13.csv',
 'ADoutput_chrom18.csv',
 'ADoutput_chrom19.csv',
 'ADoutput_chrom5.csv',
 'SNPlookupfileUKB.csv',
 'AD_sumstats_Jansenetal_2019sept.txt',
 'PDoutput_chrom2.csv',
 'chrom4snpexample.csv',
 'PDoutput_chrom8.csv',
 'PDoutput_chrom6.csv',
 'ADoutput_chrom11.csv',
 'PDoutput_chrom16.csv',
 'PDoutput_chrom4.csv',
 'ADoutput_chrom1.csv',
 'PDoutput_chrom14.csv',
 'PDoutput_chrom1.csv',
 'ADoutput_chrom2.csv']

In [66]:
chrom1=pd.read_csv('%s%s' % (path,'PDoutput_chrom1.csv'),sep='\t',header=None)
chrom2=pd.read_csv('%s%s' % (path,'PDoutput_chrom2.csv'),sep='\t',header=None)
chrom3=pd.read_csv('%s%s' % (path,'PDoutput_chrom3.csv'),sep='\t',header=None)
chrom4=pd.read_csv('%s%s' % (path,'PDoutput_chrom4.csv'),sep='\t',header=None)
chrom6=pd.read_csv('%s%s' % (path,'PDoutput_chrom6.csv'),sep='\t',header=None)
chrom8=pd.read_csv('%s%s' % (path,'PDoutput_chrom8.csv'),sep='\t',header=None)
chrom10=pd.read_csv('%s%s' % (path,'PDoutput_chrom10.csv'),sep='\t',header=None)
chrom11=pd.read_csv('%s%s' % (path,'PDoutput_chrom11.csv'),sep='\t',header=None)
chrom12=pd.read_csv('%s%s' % (path,'PDoutput_chrom12.csv'),sep='\t',header=None)
chrom13=pd.read_csv('%s%s' % (path,'PDoutput_chrom13.csv'),sep='\t',header=None)
chrom14=pd.read_csv('%s%s' % (path,'PDoutput_chrom14.csv'),sep='\t',header=None)
chrom16=pd.read_csv('%s%s' % (path,'PDoutput_chrom16.csv'),sep='\t',header=None)

In [141]:
ADchrom1=pd.read_csv('%s%s' % (path,'ADoutput_chrom1.csv'),sep='\t',header=None)
ADchrom2=pd.read_csv('%s%s' % (path,'ADoutput_chrom2.csv'),sep='\t',header=None)
ADchrom5=pd.read_csv('%s%s' % (path,'ADoutput_chrom5.csv'),sep='\t',header=None)
ADchrom7=pd.read_csv('%s%s' % (path,'ADoutput_chrom7.csv'),sep='\t',header=None)
ADchrom8=pd.read_csv('%s%s' % (path,'ADoutput_chrom8.csv'),sep='\t',header=None)
#ADchrom9=pd.read_csv('%s%s' % (path,'ADoutput_chrom9.csv'),sep='\t',header=None)
ADchrom11=pd.read_csv('%s%s' % (path,'ADoutput_chrom11.csv'),sep='\t',header=None)
ADchrom14=pd.read_csv('%s%s' % (path,'ADoutput_chrom14.csv'),sep='\t',header=None)
ADchrom18=pd.read_csv('%s%s' % (path,'ADoutput_chrom18.csv'),sep='\t',header=None)
ADchrom19=pd.read_csv('%s%s' % (path,'ADoutput_chrom19.csv'),sep='\t',header=None)
ADchrom20=pd.read_csv('%s%s' % (path,'ADoutput_chrom20.csv'),sep='\t',header=None)

In [142]:
SNPlookupAD=pd.read_csv('%s%s' % (path,'SNPlookupfileUKB_ADSNPs.csv'))

In [144]:
files=[chrom1,chrom2,chrom3,chrom4,chrom6,chrom8,chrom10,chrom11,chrom12,chrom13,chrom14,chrom16]
def colrename(file,chrom=1,df=SNPlookup,var='Risk Variant'):
    mask_chrom=(df['Chromosome']==chrom)
    if file.shape[1]-6!=df[mask_chrom].shape[0]:
        print(str(chrom)+" fail")
        df_out=file[[m for m in range(file.shape[1]) if m==1 or m>5]]
        df_out.columns=np.append('eid',['chrom'+str(chrom)+str(m) for m in range(file.shape[1]) if m>5])
    else:
        print(str(chrom)+" success")
        df_out=file[[m for m in range(file.shape[1]) if m==1 or m>5]]
        df_out.columns=np.append('eid',[x for x in df[mask_chrom][var]])
        
    return df_out

In [147]:
ADchrom1_rn=colrename(ADchrom1,1,SNPlookupAD,'SNP')
ADchrom2_rn=colrename(ADchrom2,2,SNPlookupAD,'SNP')
ADchrom5_rn=colrename(ADchrom5,5,SNPlookupAD,'SNP')
ADchrom7_rn=colrename(ADchrom7,7,SNPlookupAD,'SNP')
ADchrom8_rn=colrename(ADchrom8,8,SNPlookupAD,'SNP')
ADchrom11_rn=colrename(ADchrom11,11,SNPlookupAD,'SNP')
ADchrom14_rn=colrename(ADchrom14,14,SNPlookupAD,'SNP')
ADchrom18_rn=colrename(ADchrom18,18,SNPlookupAD,'SNP')
ADchrom19_rn=colrename(ADchrom19,19,SNPlookupAD,'SNP')
ADchrom20_rn=colrename(ADchrom20,20,SNPlookupAD,'SNP')

1 success
2 success
5 success
7 success
8 success
11 success
14 success
18 success
19 success
20 success

In [145]:
chrom1_rn=colrename(chrom1,1)
chrom2_rn=colrename(chrom2,2)
chrom3_rn=colrename(chrom3,3)
chrom4_rn=colrename(chrom4,4)
chrom6_rn=colrename(chrom6,6)
chrom8_rn=colrename(chrom8,8)
chrom10_rn=colrename(chrom10,10)
chrom11_rn=colrename(chrom11,11)
chrom12_rn=colrename(chrom12,12)
chrom13_rn=colrename(chrom13,13)
chrom14_rn=colrename(chrom14,14)
chrom16_rn=colrename(chrom16,16)

1 fail
2 fail
3 success
4 success
6 fail
8 success
10 success
11 success
12 success
13 success
14 success
16 success

In [121]:
from functools import reduce
dfs=[chrom1_rn,chrom2_rn,chrom3_rn,chrom4_rn,chrom6_rn,chrom8_rn,chrom10_rn,chrom11_rn,chrom12_rn,
     chrom13_rn,chrom14_rn,chrom16_rn]
df_final = reduce(lambda left,right: pd.merge(left,right,on='eid'), dfs)

In [124]:
ohe_cols=[col for col in df_final.columns if col!='eid']
df_ohe=pd.get_dummies(df_final[ohe_cols], prefix=ohe_cols)
df_ohe['eid']=df_final['eid']

In [148]:
dfsAD=[ADchrom1_rn,ADchrom2_rn,ADchrom5_rn,ADchrom7_rn,ADchrom8_rn,ADchrom11_rn
       ,ADchrom14_rn,ADchrom18_rn,ADchrom19_rn,ADchrom20_rn]
df_final_AD = reduce(lambda left,right: pd.merge(left,right,on='eid'), dfsAD)

In [161]:
ohe_cols_AD=[col for col in df_final_AD.columns if col!='eid']
df_ohe_AD=pd.get_dummies(df_final_AD[ohe_cols_AD], prefix=ohe_cols_AD)
df_ohe_AD['eid']=df_final_AD['eid']

In [162]:
df_ohe_AD

,rs3818361_0 0,rs3818361_A A,rs3818361_A G,rs3818361_G G,rs744373_0 0,rs744373_A A,rs744373_G A,rs744373_G G,rs35349669_0 0,rs35349669_C C,...,rs8093731_T T,rs3865444_0 0,rs3865444_A A,rs3865444_A C,rs3865444_C C,rs7274581_0 0,rs7274581_C C,rs7274581_C T,rs7274581_T T,eid
0,0,0,0,1,0,1,0,0,0,0,...,0,0,0,1,0,0,0,0,1,1403239
1,0,0,1,0,0,0,1,0,0,1,...,0,0,0,1,0,1,0,0,0,5878175
2,0,0,0,1,0,1,0,0,0,0,...,0,0,0,0,1,0,0,1,0,3424148
3,0,0,0,1,0,0,1,0,0,1,...,0,0,1,0,0,0,0,1,0,1877932
4,0,0,0,1,0,0,1,0,0,0,...,0,0,0,1,0,0,0,1,0,4612594
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
488372,0,0,0,1,0,1,0,0,1,0,...,0,0,0,1,0,1,0,0,0,5831674
488373,0,0,0,1,0,0,1,0,1,0,...,0,0,0,1,0,1,0,0,0,1218831
488374,0,0,0,1,0,1,0,0,1,0,...,0,0,1,0,0,1,0,0,0,1056269
488375,0,0,0,1,0,0,1,0,1,0,...,0,0,0,0,1,1,0,0,0,3806522
488376,0,1,0,0,0,0,1,0,1,0,...,0,0,0,1,0,1,0,0,0,5875788

In [126]:
df_ohe

,chrom16_0 0,chrom16_C C,chrom16_C T,chrom16_T T,chrom26_0 0,chrom26_A A,chrom26_G A,chrom26_G G,rs6808178_0 0,rs6808178_C C,...,rs11158026_T T,rs979812_0 0,rs979812_G G,rs979812_T G,rs979812_T T,rs2904880_0 0,rs2904880_C C,rs2904880_C G,rs2904880_G G,eid
0,0,1,0,0,0,1,0,0,0,0,...,0,0,0,1,0,0,0,1,0,1403239
1,0,1,0,0,0,1,0,0,0,0,...,0,0,0,1,0,0,0,1,0,5878175
2,0,0,1,0,0,0,1,0,0,1,...,0,0,0,1,0,0,0,1,0,3424148
3,0,0,1,0,0,1,0,0,0,0,...,0,0,0,0,1,0,0,0,1,1877932
4,0,0,0,1,0,1,0,0,0,0,...,0,0,1,0,0,0,0,1,0,4612594
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
488372,1,0,0,0,0,1,0,0,1,0,...,0,1,0,0,0,0,0,0,1,5831674
488373,1,0,0,0,0,1,0,0,1,0,...,0,1,0,0,0,0,0,1,0,1218831
488374,1,0,0,0,0,0,1,0,1,0,...,0,1,0,0,0,0,0,1,0,1056269
488375,1,0,0,0,0,1,0,0,1,0,...,0,1,0,0,0,0,0,0,1,3806522
488376,1,0,0,0,0,0,1,0,1,0,...,0,1,0,0,0,0,0,1,0,5875788

In [135]:
PD_model_full70=pd.read_pickle('%s%s' % (path_model,'PD_model_full70.p'))

In [136]:
PD_model_full70=pd.merge(PD_model_full70,df_ohe,on='eid',how='inner')

In [153]:
AD_model_full70=pd.read_pickle('%s%s' % (path_model,'AD_model_full70.p'))

In [163]:
AD_model_full70SNP=pd.merge(AD_model_full70,df_ohe_AD,on='eid',how='inner')

In [138]:
PD_model_full70.to_pickle('%s%s' % (path_model,'PD_model_full70_snp.p'))

In [165]:
AD_model_full70SNP.to_pickle('%s%s' % (path_model,'AD_model_full70SNP.p'))

In [164]:
findcols(AD_model_full70SNP,'rs')

['number_of_selfreported_cancers_f134_0.0',
 'number_of_selfreported_cancers_f134_1.0',
 'number_of_selfreported_cancers_f134_2.0',
 'number_of_selfreported_cancers_f134_3.0',
 'number_of_selfreported_cancers_f134_4.0',
 'number_of_selfreported_cancers_f134_5.0',
 'number_of_selfreported_cancers_f134_6.0',
 'number_of_selfreported_cancers_f134_Unknown',
 'own_or_rent_accommodation_lived_in_f680_Pay part rent and part mortgage (shared ownership)',
 'length_of_mobile_phone_use_f1110_Five to eight years',
 'length_of_mobile_phone_use_f1110_More than eight years',
 'length_of_mobile_phone_use_f1110_Two to four years',
 'weekly_usage_of_mobile_phone_in_last_3_months_f1120_1-3 hours',
 'weekly_usage_of_mobile_phone_in_last_3_months_f1120_4-6 hours',
 'weekly_usage_of_mobile_phone_in_last_3_months_f1120_More than 6 hours',
 'difference_in_mobile_phone_use_compared_to_two_years_previously_f1140_Do not know',
 "difference_in_mobile_phone_use_compared_to_two_years_previously_f1140_I didn't use a mobile phone two years ago",
 'difference_in_mobile_phone_use_compared_to_two_years_previously_f1140_No',
 'difference_in_mobile_phone_use_compared_to_two_years_previously_f1140_Prefer not to answer',
 'difference_in_mobile_phone_use_compared_to_two_years_previously_f1140_Unknown',
 'difference_in_mobile_phone_use_compared_to_two_years_previously_f1140_Yes, use is now less frequent',
 'difference_in_mobile_phone_use_compared_to_two_years_previously_f1140_Yes, use is now more frequent',
 "morningevening_person_chronotype_f1180_Definitely a 'morning' person",
 "morningevening_person_chronotype_f1180_Definitely an 'evening' person",
 'morningevening_person_chronotype_f1180_Do not know',
 "morningevening_person_chronotype_f1180_More a 'morning' than 'evening' person",
 "morningevening_person_chronotype_f1180_More an 'evening' than a 'morning' person",
 'morningevening_person_chronotype_f1180_Prefer not to answer',
 'morningevening_person_chronotype_f1180_Unknown',
 'smokingsmokers_in_household_f1259_No',
 'smokingsmokers_in_household_f1259_Prefer not to answer',
 'smokingsmokers_in_household_f1259_Unknown',
 'smokingsmokers_in_household_f1259_Yes, more than one household member smokes',
 'smokingsmokers_in_household_f1259_Yes, one household member smokes',
 'major_dietary_changes_in_the_last_5_years_f1538_No',
 'major_dietary_changes_in_the_last_5_years_f1538_Prefer not to answer',
 'major_dietary_changes_in_the_last_5_years_f1538_Unknown',
 'major_dietary_changes_in_the_last_5_years_f1538_Yes, because of illness',
 'major_dietary_changes_in_the_last_5_years_f1538_Yes, because of other reasons',
 'alcohol_intake_versus_10_years_previously_f1628_About the same',
 'alcohol_intake_versus_10_years_previously_f1628_Do not know',
 'alcohol_intake_versus_10_years_previously_f1628_Less nowadays',
 'alcohol_intake_versus_10_years_previously_f1628_More nowadays',
 'alcohol_intake_versus_10_years_previously_f1628_Prefer not to answer',
 'alcohol_intake_versus_10_years_previously_f1628_Unknown',
 'ever_had_samesex_intercourse_f2159_No',
 'ever_had_samesex_intercourse_f2159_Prefer not to answer',
 'ever_had_samesex_intercourse_f2159_Unknown',
 'ever_had_samesex_intercourse_f2159_Yes',
 'wears_glasses_or_contact_lenses_f2207_No',
 'wears_glasses_or_contact_lenses_f2207_Prefer not to answer',
 'wears_glasses_or_contact_lenses_f2207_Unknown',
 'wears_glasses_or_contact_lenses_f2207_Yes',
 'fracturedbroken_bones_in_last_5_years_f2463_Do not know',
 'fracturedbroken_bones_in_last_5_years_f2463_No',
 'fracturedbroken_bones_in_last_5_years_f2463_Prefer not to answer',
 'fracturedbroken_bones_in_last_5_years_f2463_Unknown',
 'fracturedbroken_bones_in_last_5_years_f2463_Yes',
 'method_of_measuring_blood_pressure_f4081_Question not asked due to previous answers',
 'qualifications_f6138_College or University degree',
 'qualifications_f6138_Other professional qualifications eg: nursing, teaching',
 'illness_injury_bereavement_stress_in_last_2_years_f6145_Death of a close relative',
 'illness_injury_bereavement_stress_in_last_2_years_f6145_Death of a spouse or partner',
 'illness_injury_bereavement_stress_in_last_2_years_f6145_Financial difficulties',
 'illness_injury_bereavement_stress_in_last_2_years_f6145_Marital separation/divorce',
 'illness_injury_bereavement_stress_in_last_2_years_f6145_None of the above',
 'illness_injury_bereavement_stress_in_last_2_years_f6145_Prefer not to answer',
 'illness_injury_bereavement_stress_in_last_2_years_f6145_Serious illness, injury or assault of a close relative',
 'illness_injury_bereavement_stress_in_last_2_years_f6145_Serious illness, injury or assault to yourself',
 'illness_injury_bereavement_stress_in_last_2_years_f6145_Unknown',
 'mouthteeth_dental_problems_f6149_Mouth ulcers',
 'APOE4_Carriers_0.0',
 'APOE4_Carriers_1.0',
 'APOE4_Carriers_2.0',
 'APOE4_Carriers_Unknown',
 'number_of_selfreported_cancers_f134',
 'time_spend_outdoors_in_summer_f1050',
 'time_spent_outdoors_in_winter_f1060',
 'number_of_full_brothers_f1873',
 'number_of_full_sisters_f1883',
 'age_first_had_sexual_intercourse_f2139',
 'lifetime_number_of_sexual_partners_f2149',
 'inverse_distance_to_the_nearest_road_f24010',
 'inverse_distance_to_the_nearest_major_road_f24012',
 'APOE4_Carriers',
 'rs3818361_0 0',
 'rs3818361_A A',
 'rs3818361_A G',
 'rs3818361_G G',
 'rs744373_0 0',
 'rs744373_A A',
 'rs744373_G A',
 'rs744373_G G',
 'rs35349669_0 0',
 'rs35349669_C C',
 'rs35349669_T C',
 'rs35349669_T T',
 'rs190982_0 0',
 'rs190982_A A',
 'rs190982_G A',
 'rs190982_G G',
 'rs2718058_0 0',
 'rs2718058_A A',
 'rs2718058_G A',
 'rs2718058_G G',
 'rs1476679_0 0',
 'rs1476679_C C',
 'rs1476679_C T',
 'rs1476679_T T',
 'rs11771145_0 0',
 'rs11771145_A A',
 'rs11771145_A G',
 'rs11771145_G G',
 'rs11136000_0 0',
 'rs11136000_C C',
 'rs11136000_C T',
 'rs11136000_T T',
 'rs28834970_0 0',
 'rs28834970_C C',
 'rs28834970_T C',
 'rs28834970_T T',
 'rs10838725_0 0',
 'rs10838725_C T',
 'rs10838725_T T',
 'rs610932_0 0',
 'rs610932_G G',
 'rs610932_T G',
 'rs610932_T T',
 'rs3851179_0 0',
 'rs3851179_C C',
 'rs3851179_T C',
 'rs3851179_T T',
 'rs17125944_0 0',
 'rs17125944_C C',
 'rs17125944_C T',
 'rs17125944_T T',
 'rs10498633_0 0',
 'rs10498633_G G',
 'rs10498633_T G',
 'rs10498633_T T',
 'rs8093731_0 0',
 'rs8093731_C C',
 'rs8093731_T C',
 'rs8093731_T T',
 'rs3865444_0 0',
 'rs3865444_A A',
 'rs3865444_A C',
 'rs3865444_C C',
 'rs7274581_0 0',
 'rs7274581_C C',
 'rs7274581_C T',
 'rs7274581_T T']